# Generated by Django 6.0.2 on 2026-02-25 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='core_user_created_bd650f_idx'), models.Index(fields=['updated_at'], name='core_user_updated_4c12a0_idx'), models.Index(fields=['is_active'], name='core_user_is_acti_8c954f_idx')],
            },
        ),
    ]
