# Generated by Django 6.0.2 on 2026-02-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name'], 'verbose_name_plural': 'Tags'},
        ),
    ]
